Repository bids-bep001/bids-specification, pull requests merged in 2020-06, with the labels that each got.

#24 [ENH] Add transmit and receive RF field maps
  src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
  src/99-appendices/10-qmri.md
Labels: enhancement

#28 Added SA2RAGE B1+-mapping method to qmri appendix
  src/99-appendices/10-qmri.md
Labels: almost there

#37 [UPDATE] qMRI map generation options
  src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md
  src/99-appendices/10-qmri.md
Labels: enhancement, feedback needed
